package com.cimsolutions.entities;
// Generated 24-Mar-2017 10:12:06 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Baan generated by hbm2java
 */
@Entity
@Table(name = "baan", catalog = "onderhouddb")
public class Baan implements java.io.Serializable {

	private int baanId;
	private String baanNaam;
	private Integer volgorde;

	public Baan() {
	}

	public Baan(int baanId) {
		this.baanId = baanId;
	}

	public Baan(int baanId, String baanNaam, Integer volgorde) {
		this.baanId = baanId;
		this.baanNaam = baanNaam;
		this.volgorde = volgorde;
	}

	@Id

	@Column(name = "BaanID", unique = true, nullable = false)
	public int getBaanId() {
		return this.baanId;
	}

	public void setBaanId(int baanId) {
		this.baanId = baanId;
	}

	@Column(name = "BaanNaam", length = 65535)
	public String getBaanNaam() {
		return this.baanNaam;
	}

	public void setBaanNaam(String baanNaam) {
		this.baanNaam = baanNaam;
	}

	@Column(name = "Volgorde")
	public Integer getVolgorde() {
		return this.volgorde;
	}

	public void setVolgorde(Integer volgorde) {
		this.volgorde = volgorde;
	}

}
