package com.cimsolutions.entities;
// Generated 31-Mar-2017 10:55:48 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Baan generated by hbm2java
 */
@Entity
@Table(name = "baan", catalog = "onderhouddb")
public class Baan implements java.io.Serializable {

	private int id;
	private String baanNaam;
	private Integer volgorde;
	private Set<Reparatie> reparaties = new HashSet<Reparatie>(0);

	public Baan() {
	}

	public Baan(int id) {
		this.id = id;
	}

	public Baan(int id, String baanNaam, Integer volgorde, Set<Reparatie> reparaties) {
		this.id = id;
		this.baanNaam = baanNaam;
		this.volgorde = volgorde;
		this.reparaties = reparaties;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "BaanNaam", length = 65535)
	public String getBaanNaam() {
		return this.baanNaam;
	}

	public void setBaanNaam(String baanNaam) {
		this.baanNaam = baanNaam;
	}

	@Column(name = "Volgorde")
	public Integer getVolgorde() {
		return this.volgorde;
	}

	public void setVolgorde(Integer volgorde) {
		this.volgorde = volgorde;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "baan")
	public Set<Reparatie> getReparaties() {
		return this.reparaties;
	}

	public void setReparaties(Set<Reparatie> reparaties) {
		this.reparaties = reparaties;
	}

}
