package com.cimsolutions.entities;
// Generated 14-Apr-2017 09:42:28 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Deklagenlijst generated by hbm2java
 */
@Entity
@Table(name = "deklagenlijst", catalog = "onderhouddb")
public class Deklagenlijst implements java.io.Serializable {

	private Integer id;
	private String wegnummer;
	private String regionaleDirectie;
	private Integer district;
	private String baan;
	private String strook;
	private Double hectometerbordBegin;
	private Double hectometerbordEind;
	private String deklaagsoort;
	private Date aanlegdatum;

	public Deklagenlijst() {
	}

	public Deklagenlijst(String wegnummer, String regionaleDirectie, Integer district, String baan, String strook,
			Double hectometerbordBegin, Double hectometerbordEind, String deklaagsoort, Date aanlegdatum) {
		this.wegnummer = wegnummer;
		this.regionaleDirectie = regionaleDirectie;
		this.district = district;
		this.baan = baan;
		this.strook = strook;
		this.hectometerbordBegin = hectometerbordBegin;
		this.hectometerbordEind = hectometerbordEind;
		this.deklaagsoort = deklaagsoort;
		this.aanlegdatum = aanlegdatum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Wegnummer", length = 65535)
	public String getWegnummer() {
		return this.wegnummer;
	}

	public void setWegnummer(String wegnummer) {
		this.wegnummer = wegnummer;
	}

	@Column(name = "RegionaleDirectie", length = 65535)
	public String getRegionaleDirectie() {
		return this.regionaleDirectie;
	}

	public void setRegionaleDirectie(String regionaleDirectie) {
		this.regionaleDirectie = regionaleDirectie;
	}

	@Column(name = "District")
	public Integer getDistrict() {
		return this.district;
	}

	public void setDistrict(Integer district) {
		this.district = district;
	}

	@Column(name = "Baan", length = 65535)
	public String getBaan() {
		return this.baan;
	}

	public void setBaan(String baan) {
		this.baan = baan;
	}

	@Column(name = "Strook", length = 65535)
	public String getStrook() {
		return this.strook;
	}

	public void setStrook(String strook) {
		this.strook = strook;
	}

	@Column(name = "HectometerbordBegin", precision = 22, scale = 0)
	public Double getHectometerbordBegin() {
		return this.hectometerbordBegin;
	}

	public void setHectometerbordBegin(Double hectometerbordBegin) {
		this.hectometerbordBegin = hectometerbordBegin;
	}

	@Column(name = "HectometerbordEind", precision = 22, scale = 0)
	public Double getHectometerbordEind() {
		return this.hectometerbordEind;
	}

	public void setHectometerbordEind(Double hectometerbordEind) {
		this.hectometerbordEind = hectometerbordEind;
	}

	@Column(name = "Deklaagsoort", length = 65535)
	public String getDeklaagsoort() {
		return this.deklaagsoort;
	}

	public void setDeklaagsoort(String deklaagsoort) {
		this.deklaagsoort = deklaagsoort;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Aanlegdatum", length = 19)
	public Date getAanlegdatum() {
		return this.aanlegdatum;
	}

	public void setAanlegdatum(Date aanlegdatum) {
		this.aanlegdatum = aanlegdatum;
	}

}
