package com.cimsolutions.entities;
// Generated 14-Apr-2017 09:42:28 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Reparatiemethoden generated by hbm2java
 */
@Entity
@Table(name = "reparatiemethoden", catalog = "onderhouddb")
public class Reparatiemethoden implements java.io.Serializable {

	private Integer id;
	private String naam;
	private Set<Reparatie> reparaties = new HashSet<Reparatie>(0);

	public Reparatiemethoden() {
	}

	public Reparatiemethoden(String naam, Set<Reparatie> reparaties) {
		this.naam = naam;
		this.reparaties = reparaties;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "naam", length = 45)
	public String getNaam() {
		return this.naam;
	}

	public void setNaam(String naam) {
		this.naam = naam;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reparatiemethoden")
	public Set<Reparatie> getReparaties() {
		return this.reparaties;
	}

	public void setReparaties(Set<Reparatie> reparaties) {
		this.reparaties = reparaties;
	}

}
