package com.cimsolutions.entities;
// Generated 31-Mar-2017 10:55:48 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reparatie generated by hbm2java
 */
@Entity
@Table(name = "reparatie", catalog = "onderhouddb")
public class Reparatie implements java.io.Serializable {

	private Integer id;
	private Baan baan;
	private District district;
	private Strook strook;
	private Wegenlijst wegenlijst;
	private String soort;
	private String hectometerbord;
	private String verhardingssoort;
	private String reparatiemethode;
	private Date datumtijd;
	private String noodofspoed;
	private String aantalgaten;
	private String opmerking;
	private String constatering;
	private Set<Userreparatie> userreparaties = new HashSet<Userreparatie>(0);

	public Reparatie() {
	}

	public Reparatie(Baan baan, District district, Strook strook, Wegenlijst wegenlijst, String soort,
			String hectometerbord, String verhardingssoort, String reparatiemethode, Date datumtijd, String noodofspoed,
			String aantalgaten, String opmerking, String constatering, Set<Userreparatie> userreparaties) {
		this.baan = baan;
		this.district = district;
		this.strook = strook;
		this.wegenlijst = wegenlijst;
		this.soort = soort;
		this.hectometerbord = hectometerbord;
		this.verhardingssoort = verhardingssoort;
		this.reparatiemethode = reparatiemethode;
		this.datumtijd = datumtijd;
		this.noodofspoed = noodofspoed;
		this.aantalgaten = aantalgaten;
		this.opmerking = opmerking;
		this.constatering = constatering;
		this.userreparaties = userreparaties;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "baan")
	public Baan getBaan() {
		return this.baan;
	}

	public void setBaan(Baan baan) {
		this.baan = baan;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "district")
	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "strook")
	public Strook getStrook() {
		return this.strook;
	}

	public void setStrook(Strook strook) {
		this.strook = strook;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "WegenlijstId")
	public Wegenlijst getWegenlijst() {
		return this.wegenlijst;
	}

	public void setWegenlijst(Wegenlijst wegenlijst) {
		this.wegenlijst = wegenlijst;
	}

	@Column(name = "soort", length = 45)
	public String getSoort() {
		return this.soort;
	}

	public void setSoort(String soort) {
		this.soort = soort;
	}

	@Column(name = "hectometerbord", length = 45)
	public String getHectometerbord() {
		return this.hectometerbord;
	}

	public void setHectometerbord(String hectometerbord) {
		this.hectometerbord = hectometerbord;
	}

	@Column(name = "verhardingssoort", length = 45)
	public String getVerhardingssoort() {
		return this.verhardingssoort;
	}

	public void setVerhardingssoort(String verhardingssoort) {
		this.verhardingssoort = verhardingssoort;
	}

	@Column(name = "reparatiemethode", length = 45)
	public String getReparatiemethode() {
		return this.reparatiemethode;
	}

	public void setReparatiemethode(String reparatiemethode) {
		this.reparatiemethode = reparatiemethode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datumtijd", length = 19)
	public Date getDatumtijd() {
		return this.datumtijd;
	}

	public void setDatumtijd(Date datumtijd) {
		this.datumtijd = datumtijd;
	}

	@Column(name = "noodofspoed", length = 45)
	public String getNoodofspoed() {
		return this.noodofspoed;
	}

	public void setNoodofspoed(String noodofspoed) {
		this.noodofspoed = noodofspoed;
	}

	@Column(name = "aantalgaten", length = 45)
	public String getAantalgaten() {
		return this.aantalgaten;
	}

	public void setAantalgaten(String aantalgaten) {
		this.aantalgaten = aantalgaten;
	}

	@Column(name = "opmerking")
	public String getOpmerking() {
		return this.opmerking;
	}

	public void setOpmerking(String opmerking) {
		this.opmerking = opmerking;
	}

	@Column(name = "constatering", length = 45)
	public String getConstatering() {
		return this.constatering;
	}

	public void setConstatering(String constatering) {
		this.constatering = constatering;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reparatie")
	public Set<Userreparatie> getUserreparaties() {
		return this.userreparaties;
	}

	public void setUserreparaties(Set<Userreparatie> userreparaties) {
		this.userreparaties = userreparaties;
	}

}
