package com.cimsolutions.entities;
// Generated 14-Apr-2017 09:42:28 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Strook generated by hbm2java
 */
@Entity
@Table(name = "strook", catalog = "onderhouddb")
public class Strook implements java.io.Serializable {

	private int id;
	private String strook;
	private Integer volgorde;

	public Strook() {
	}

	public Strook(int id) {
		this.id = id;
	}

	public Strook(int id, String strook, Integer volgorde) {
		this.id = id;
		this.strook = strook;
		this.volgorde = volgorde;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Strook", length = 65535)
	public String getStrook() {
		return this.strook;
	}

	public void setStrook(String strook) {
		this.strook = strook;
	}

	@Column(name = "Volgorde")
	public Integer getVolgorde() {
		return this.volgorde;
	}

	public void setVolgorde(Integer volgorde) {
		this.volgorde = volgorde;
	}

}
