package com.cimsolutions.entities;
// Generated 10-Apr-2017 10:46:59 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Userreparatie generated by hbm2java
 */
@Entity
@Table(name = "userreparatie", catalog = "onderhouddb")
public class Userreparatie implements java.io.Serializable {

	private Integer id;
	private Apuser apuser;
	private Reparatie reparatie;

	public Userreparatie() {
	}

	public Userreparatie(Apuser apuser, Reparatie reparatie) {
		this.apuser = apuser;
		this.reparatie = reparatie;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "apuserid")
	public Apuser getApuser() {
		return this.apuser;
	}

	public void setApuser(Apuser apuser) {
		this.apuser = apuser;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "reparatieid")
	public Reparatie getReparatie() {
		return this.reparatie;
	}

	public void setReparatie(Reparatie reparatie) {
		this.reparatie = reparatie;
	}

}
